global using System;
global using System.Collections.Generic;
global using System.Linq; 
global using System.Text;
global using System.Threading.Tasks;
global using Pet_Doc_BE_Domain.Models;
global using Pet_Doc_BE_Domain.Models.Doctor;
global using Pet_Doc_BE_Application.Contracts;
global using Pet_Doc_BE_Infrastructure.Persistence;
global using static Pet_Doc_BE_Domain.Models.ModelConstants.Common;